# This is a basic workflow to help you get started with Actions

# name: Update docker images

# on:
#   schedule:
#   - cron: "0 0 * * 2/3"
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     name: Update docker images
#     runs-on: [ubuntu-latest]
#     steps:
#       - run: curl --silent --show-error --fail -X POST ${{ secrets.DOCKER_HUB_BUILD_TRIGGER_URL }}
